### ISSUE TITLE
Does this package converts `multi_line_text_field` to `rich_text_field`?

### ISSUE THREAD

**Issue by remy727** [TheBeyondGroup/shopify-rich-text-renderer#3]
I want to migrate `multi_line_text_field` to `rich_text_field`

```
# Before
<p>test</p>

# After
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "test"
        }
      ]
    }
  ]
}
```
Can I use this package for this migration?

**Comment by mcqua007** [comment]
@remy727 You might be able to, I am not fully grasping what you are trying to do though. Can you provide more context ?

If you need to convert Shopify richtext to HTML than this package should help.

**Comment by remy727** [comment]
Hi @mcqua007, can I also use this package to convert HTML to Shopify richtext?

**Comment by mcqua007** [comment]
> Hi @mcqua007, can I also use this package to convert HTML to Shopify richtext?

@remy727  No, unfortunately this only goes one way. Mainly because Shopify's rich text is very limited. It only has few different types of elements (headings, paragraph, text, lists, and list-items) etc... This would mean the HTML could only have these tags and would fail to convert.

I am not sure why you would need to convert HTML to Shopify's Richtext ? What is your use case ? 

Doing essentially the reverse as what I did here. Maybe using [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString). You can iterate through level of HTML and make the correct object.

**Comment by remy727** [comment]
Hi @mcqua007, thank you for answering. Makes sense.
I need to migrate the old app metafield(textfield/html) to a new metaobject(richtext).

**Comment by mcqua007** [comment]
@remy727 That makes sense, that could be difficult for the reasons I outlined above. Through if the HTML has only those elements it could be done.

**Comment by remy727** [comment]
Got it. Thank you for your support. We can close this now.

**Comment by mcqua007** [comment]
@remy727 Yep, no problem! Have a good day!
